services:
  redis:
    image: redis:7-alpine
    container_name: project-redis
    restart: unless-stopped

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: project-rabbitmq
    restart: unless-stopped

    ports:
      # 애플리케이션이 RabbitMQ에 접속하는 포트
      - "5672:5672"

      # RabbitMQ Management UI
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  redis_data:
  rabbitmq_data:
