spring:
  config:
    import: "optional:file:./.env[.properties]"
  ai:
    openai:
      base-url: "${GMS_ENDPOINT}/api.openai.com/v1"
      api-key: "${GMS_KEY:}"
      chat:
        model: "${GMS_MODEL:gpt-5.4-mini}"
        temperature: 0.4
  datasource:
    url: "${POSTGRESQL_URL}"
    username: "${POSTGRESQL_USERNAME}"
    password: "${POSTGRESQL_PASSWORD}"
    port: "${POSTGRESQL_PORT}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"
  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 550MB

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:/}
    dynamic: true

    connection-timeout: 5s
    requested-heartbeat: 30s

    # RabbitMQ가 메시지를 정상적으로 받았는지 확인
    publisher-confirm-type: correlated

    # Exchange에 발행했지만 Queue로 라우팅되지 않은 경우 확인
    publisher-returns: true

    template:
      mandatory: true

jwt:
  secret-key: "${JWT_SECRET_KEY}"
  access-token-expiration-milliseconds: "${JWT_ACCESS_TOKEN_EXPIRATION_MILLISECONDS:86400000}"

aws:
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: "${AWS_S3_BUCKET:}"
    region: "${AWS_REGION:ap-northeast-2}"

security:
  password:
    secret-key: "${PASSWORD_SECRET_KEY}"
fastapi:
  base-url: "${FASTAPI_BASE_URL:http://localhost:8090}"
